#!/usr/bin/env python
# -- Content-Encoding: UTF-8 --
"""
Extracts the release notes of a version from ``docs/changelog.md``.

The changelog is the single source of truth for what a release contains: the
notes shown on the GitHub release page are generated from it rather than
written a second time by hand.

The script also refuses to produce notes for a release whose date is still
``Unreleased``, which makes it the last guard before a tag is published.

The changelog uses a reStructuredText ``:Release Date:`` field under each
``## <version>`` heading. The heading may be the full version (``## 0.6.0``)
or the conventional short form (``## 0.6`` for the ``0.6.0`` release): both
are accepted.

This script is CI-only tooling and never shipped, so it is Python 3 only.

:authors: Thomas Calmant
:license: Apache License 2.0
:version: 1.0.0

..

    Copyright 2026 Thomas Calmant

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

import argparse
import pathlib
import re
import sys

# Module version
__version_info__ = (1, 0, 0)
__version__ = ".".join(str(x) for x in __version_info__)

# Documentation strings format
__docformat__ = "restructuredtext en"

#: Root of the repository, i.e. the parent of ``.github``
ROOT = pathlib.Path(__file__).resolve().parents[2]

#: The reStructuredText field holding the release date
DATE_FIELD_PATTERN = re.compile(r"^:Release Date:\s*(.+?)\s*$", re.MULTILINE)

#: Footer explaining how to check the integrity of the published artifacts
VERIFICATION_FOOTER = """
## Verifying this release

Each artifact published on PyPI carries a
[PEP 740](https://peps.python.org/pep-0740/) attestation, generated by the
`publish.yml` workflow through PyPI Trusted Publishing: no long-lived token is
involved, and the attestation is visible on the PyPI page of each file.

The same artifacts are attached below, together with their CycloneDX Software
Bill of Materials, and are covered by a SLSA build provenance attestation:

```bash
gh attestation verify <downloaded file> --repo {repository}
git tag -v {tag}
```
"""


def heading_candidates(version):
    """
    Returns the changelog headings that may describe the given version, most
    specific first: the full version, then the same version with trailing
    ``.0`` groups removed (``0.6.0`` -> ``0.6``), matching the project's
    convention of heading a release with its short version.

    :param version: Version to look for, e.g. ``0.6.0``
    :return: A list of candidate heading titles
    """
    parts = version.split(".")
    candidates = []
    while parts:
        candidate = ".".join(parts)
        if candidate not in candidates:
            candidates.append(candidate)
        if parts[-1] != "0":
            break
        parts = parts[:-1]
    return candidates


def find_section(changelog, version):
    """
    Extracts the section of the changelog describing the given version

    :param changelog: Content of the changelog
    :param version: Version to look for
    :return: The content of the section, without its title
    :raise KeyError: No section found for that version
    """
    lines = changelog.splitlines()
    titles = [
        "## {0}".format(candidate) for candidate in heading_candidates(version)
    ]

    for title in titles:
        try:
            start = next(
                idx for idx, line in enumerate(lines) if line.strip() == title
            )
        except StopIteration:
            continue

        end = next(
            (
                idx
                for idx, line in enumerate(lines[start + 1 :], start + 1)
                if line.startswith("## ")
            ),
            len(lines),
        )
        return "\n".join(lines[start + 1 : end]).strip()

    raise KeyError(
        "No section in the changelog for version {0} (tried {1})".format(
            version, ", ".join(repr(t) for t in titles)
        )
    )


def split_date(section):
    """
    Separates the release date from the body of a changelog section

    :param section: Content of a changelog section
    :return: A (date, body) tuple
    :raise ValueError: The section has no ':Release Date:' field
    """
    match = DATE_FIELD_PATTERN.search(section)
    if match is None:
        raise ValueError("No ':Release Date:' field in the section")

    body = (section[: match.start()] + section[match.end() :]).strip()
    return match.group(1).strip(), body


def main():
    """
    Script entry point

    :return: The exit code of the script
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("version", help="Version to extract, e.g. 0.6.0")
    parser.add_argument(
        "-o", "--output", help="File to write the notes to (default: stdout)"
    )
    parser.add_argument(
        "--tag",
        help="Release tag, used in the verification instructions "
        "(default: the version)",
    )
    parser.add_argument(
        "--repository",
        default="tcalmant/python-javaobj",
        help="GitHub repository, used in the verification instructions",
    )
    parser.add_argument(
        "--changelog",
        default=str(ROOT / "docs" / "changelog.md"),
        help="Path to the changelog",
    )
    args = parser.parse_args()

    tag = args.tag or args.version
    changelog_url = (
        "https://github.com/{0}/blob/master/docs/changelog.md".format(
            args.repository
        )
    )

    changelog = pathlib.Path(args.changelog).read_text(encoding="utf-8")
    try:
        section = find_section(changelog, args.version)
        date, body = split_date(section)
    except (KeyError, ValueError) as ex:
        print("::error::{0}".format(ex), file=sys.stderr)
        return 1

    if date.lower() == "unreleased":
        print(
            "::error::version {0} is still marked as 'Unreleased' in the "
            "changelog".format(args.version),
            file=sys.stderr,
        )
        return 1

    header = (
        "Released on {0}. The complete release notes are available in "
        "[the changelog]({1}).".format(date, changelog_url)
    )
    notes = "\n".join(
        (
            header,
            "",
            body,
            "",
            VERIFICATION_FOOTER.format(
                repository=args.repository, tag=tag
            ).strip(),
            "",
        )
    )

    if args.output:
        pathlib.Path(args.output).write_text(notes, encoding="utf-8")
    else:
        sys.stdout.write(notes)
    return 0


if __name__ == "__main__":
    sys.exit(main())
